### PR TITLE
feat/signupActivity

### PR DESCRIPTION
**Pull request by peculiaruc**
feat:Refactored SignupActivity

### CODE REVIEW

**Review by mayokunadeniyi — COMMENTED** [review]
@peculiaruc you still haven't attached screenshots here. I'm referring to this comment section. Just drag and drop it here and click the comment button.

**Comment by peculiaruc** [comment]
Screenshot_20200701-183052
Screenshot_20200701-183103
Screenshot_20200701-183927

https://github.com/hngi/mobileforce-HomeTeach/pull/51

**Comment by peculiaruc** [comment]
I dragged and dropped before but didn/t click on the comment I guess.

**Review by mayokunadeniyi — CHANGES_REQUESTED** [review]
Hi @peculiaruc awesome stuff here. Could you please add some margin to the country flags in the Phone number section for the screens. Also your "I have read the term and condition" should be "terms and conditions"

**Comment by peculiaruc** [comment]
Ok

**Comment by mayokunadeniyi** [comment]
@peculiaruc would love to see some screenshots of the change 👀

**Comment by peculiaruc** [comment]
Screenshot_20200702-043526

https://github.com/hngi/mobileforce-HomeTeach/pull/51

**Comment by peculiaruc** [comment]
https://github.com/hngi/mobileforce-HomeTeach/pull/51

**Comment by mayokunadeniyi** [comment]
@peculiaruc awesome stuff! One last thing, could you please pull the recent updates from this branch. There's a merge conflict and the Merge pull request button has been disabled

**Comment by peculiaruc** [comment]
Done.
Please confirm

**Review by mayokunadeniyi — APPROVED** [review]
@peculiaruc we are go for green on the merge! 👍 Thank you.

**Pull request merged**
