### PR TITLE
feat/fix/signinActivity

### PR DESCRIPTION
**Pull request by peculiaruc**
feat: fixed LogIn Activity and XML

### CODE REVIEW

**Comment by peculiaruc** [comment]
Screenshot from 2020-07-08 10-21-41

**Comment by peculiaruc** [comment]
https://github.com/hngi/mobileforce-HomeTeach/pull/100/

**Comment by mayorjay** [comment]
@peculiaruc the build fails. Please ensure that everything works perfectly before making the PR. I can't merge with such red flag
build_fail

**Comment by peculiaruc** [comment]
Please what is the error?

**Comment by mayorjay** [comment]
@peculiaruc I will suggest you make a new PR after pulling the latest updates from this Repo. If it doesn't show something like this one below, it's not safe to merge
build_pass

**Comment by peculiaruc** [comment]
Alright I am on it

**Comment by mayorjay** [comment]
Great!

**Pull request merged**
