### PR TITLE
Feat/Withdrawal Sreens

### PR DESCRIPTION
**Pull request by dolapobabs**
Make Withdrawal screen
My Bank Screen
Card Details Screen

### CODE REVIEW

**Comment by dolapobabs** [comment]
image
image
image

**Review by mayokunadeniyi — CHANGES_REQUESTED** [review]
Hello @dolapobabs your code LGTM! 👍  

I only have an issue with the package structure. We are trying to keep it very organised. I would suggest that under `ui` you create one package for `withdrawalscreens` there all the `mybank`, `withdrawal` and `carddetails` would go into. Also I noticed you put your adapters in the adapters folder. I would also suggest you move it into the `ui/withdrawalscreens` then just create a package to house your adapters there i.e. `ui/withdrawalscreens/adapters`. We would be refactoring later on to delete that package where you currently have your adapters. Can we achieve this ?

**Comment by dolapobabs** [comment]
Done. Refractored using the package structure suggested

**Review by mayokunadeniyi — APPROVED** [review]
Awesome!

**Pull request merged**
