### PR TITLE
Parent student homepage

### PR DESCRIPTION
**Pull request by ghost**
Made another Pulll Request

### CODE REVIEW

**Comment by wadva474** [comment]
please pull from the develop branch before pushing 
you have some conflicting files

**Review by ayevbeosa — CHANGES_REQUESTED** [review]
One more thing @mikailyusuf, please use a different Activity for the Parent Student Home page. The main activity is meant to be blank for now.
You don't have to close this PR, just make the changes locally and push.

**Comment by ghost** [comment]
Just did that

On Saturday, June 20, 2020, Ayevbeosa Iyamu <notifications@github.com>
wrote:
> @ayevbeosa requested changes on this pull request.
>
> One more thing @mikailyusuf, please use a different Activity for the
Parent Student Home page. The main activity is meant to be blank for now.
> You don't have to close this PR, just make the changes locally and push.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/3NF3ZzyYX-ygnWAG7ghZzx0t9zBMV119-qB8El7D3IyJydpblD2xQz6uHJiOGndcUd62nojwHIYOJEhgrEP9enjiUEpsucMHz7AK6FCS4PPq0EwuNq5qpYfuuLWrC1pU51sIVXBiWEGysaOm80MCkwuB95EZGj0qwQ7KsFbS4bzs47aGFuYJHapoh6vHP5DXz8E87VzeLD5eeun62AUSKDD_PQa1xQ5ccdYSvmCQ87XOgeursOFc=s0-d-e1-ft#https://github.com/notifications/beacon/APZHNCTGVYBJKKUXDLLO2QTRXUNGLA5CNFSM4ODQSGDKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGODHSTRZY.gif>

**Review by ayevbeosa — COMMENTED** [review]
I noticed you renamed the `MainActivity` file which is not what I requested. What you're meant to do is to create a different file for your `BottomNavigation`

**Pull request closed without merging**
