### PR TITLE
Tutors Details

### PR DESCRIPTION
**Pull request by ghost**
Screenshot_20200710-180528
Screenshot_20200710-180534
Screenshot_20200710-180539

### CODE REVIEW

**Comment by enyason** [comment]
okay cool. Please what action brings up the date dialog @mikailkyusuf

**Comment by ghost** [comment]
Request service button

**Comment by ghost** [comment]
When the student wants to use the service of the tutor he clicks on the request service button to pick a date for his classes

**Comment by ghost** [comment]
Screenshot from 2020-07-10 21-45-38

**Review by mayokunadeniyi — APPROVED** [review]
LGTM!

**Pull request merged**
