### PR TITLE
feat/Notification Layout

### PR DESCRIPTION
**Pull request by raiyan-aegon**
Designed the Notification for the tutors and how each element in the notification will look , all in the xml.

Link to club house story : https://app.clubhouse.io/startng/story/52109/notification-fragment-layout

### CODE REVIEW

**Comment by mayokunadeniyi** [comment]
Hello boss @raiyan-aegon this LGTM! just a little check, can you please attach screenshots for these three layout files ? `app/src/main/res/layout/fragment_notification_tutor.xml` `app/src/main/res/layout/notification_item.xml` `app/src/main/res/layout/notification_new_item.xml`

**Review by mayokunadeniyi — COMMENTED** [review]
LGTM! 👍

**Comment by raiyan-aegon** [comment]
Screenshot_20200622-084409

**Comment by raiyan-aegon** [comment]
Screenshot_20200622-084409

**Comment by dev-juri** [comment]
Kindly adjust the color of the Appbar

**Comment by mayokunadeniyi** [comment]
Awesome!

**Comment by mayokunadeniyi** [comment]
> Kindly adjust the color of the Appbar

Yeah..I don't think he touched that in his commits

**Pull request merged**
