### PR TITLE
Built login activity

### PR DESCRIPTION
**Pull request by onumengine**
Slack username: @Champ
My Clubhouse ticket link: https://app.clubhouse.io/startng/story/48771/login-layout

### CODE REVIEW

**Review by ayevbeosa — CHANGES_REQUESTED** [review]
Please import the `R` class in your LoginActivity. 
Concerning the font if it part of the what is specified in the design add the font directly not as a downloadable font else remove it.

**Comment by onumengine** [comment]
This build error is not from my end just in case. It's from the onUserClick method in some fragment I didn't build

**Comment by onumengine** [comment]
Okay. On it

**Comment by onumengine** [comment]
I'm done with the changes @ayevbeosa

**Review by ayevbeosa — APPROVED** [review]

**Pull request merged**
